shell = { program = "/bin/zsh", args = ["-l"] }
live_config_reload = true

[window]
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
size = 16.0
